name: Generate Snake Animation

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: cooingcy
          outputs: |
            dist/ocean.svg?color_snake=gradient#1E3A8A-0.3-#3B82F6-0.7-#60A5FA-1.0
            dist/ocean-dark.svg?color_snake=gradient#1E3A8A-0.3-#3B82F6-0.7-#60A5FA-1.0
            &color_dots=#0ea5e9,#0284c7,#0369a1,#0c4a6e

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
